In [2]:

typealias CV Array{Complex{Float64},1}
typealias CT Tuple{Complex{Float64},Complex{Float64}}
typealias CM Array{Complex{Float64},2}

type Qubit 
    state::CT
end


Base.convert(::Type{CV}, b::Qubit) = [b.state[1]; b.state[2]]

Qubit(val::Bool) = Qubit( (val==false,val==true) )
Qubit(val::Int) = if (val == 0 || val == 1 )
    Qubit( (val==0,val==1))
else
    throw( DomainError())
end
Qubit(val::Array{Number,1}) = if (len(val) == 2)
    Qubit( (val[1],val[2]) )
else
    throw(TypeError())
end


function is_normalized(b::Qubit)
    return abs(b.state[1])^2 + abs(b.state[2])^2 == 1.0
end

b = Qubit((0,0))
display(b)
#convert(CV, b)
#Qubit([0,0])
is_normalized(b)

Qubit((0.0 + 0.0im,0.0 + 0.0im))

false

In [3]:
## this is more cosmic if any bits are entangled.  Perhaps go to NxN?

type Qureg
    bits::Array{Qubit,1}
end

Base.convert(::Type{CV}, r::Qureg) = reduce(vcat, map(x->convert(CV,x),r.bits))
convert(CV,b)
r = Qureg([b,b,b])
convert(CV, r)

6-element Array{Complex{Float64},1}:
 0.0+0.0im
 0.0+0.0im
 0.0+0.0im
 0.0+0.0im
 0.0+0.0im
 0.0+0.0im

In [4]:
abstract BasicGate

abstract MatrixGate <: BasicGate

Base.:|(g::MatrixGate, b::Qubit) = (g.m)*convert(CV,b)
Base.:|(g::MatrixGate, g2::MatrixGate) = (g.m)*(g2.m)
Base.:|(m::CM, b::Qubit) = m*convert(CV,b)
Base.convert(::Type{CM}, m::MatrixGate) = m.m

type BitwiseMatrixGate <: MatrixGate
    m::CM
end

function expanded_bitwise_matrix(g::BitwiseMatrixGate, nbits::Integer)
    result = zeros((2*nbits, 2*nbits))
    for i in 1:nbits
        result[2*i-1:2*i, 2*i-1:2*i] = g.m
    end
    result
end

Base.:|(g::BitwiseMatrixGate, r::Qureg) = expanded_bitwise_matrix(g, length(r.bits))*convert(CV,r)
import Base: *


#function X(b::Qubit)
#    let m = [0 1; 1 0]
#        m*b
#    end
#end

X = BitwiseMatrixGate([0 1; 1 0])

#X() = X([0 1; 
#         1 0])
display(X|b)
display(X|X|b)
display(r)
display(X|r)

2-element Array{Complex{Float64},1}:
 0.0+0.0im
 0.0+0.0im

2-element Array{Complex{Float64},1}:
 0.0+0.0im
 0.0+0.0im

Qureg(Qubit[Qubit((0.0+0.0im,0.0+0.0im)),Qubit((0.0+0.0im,0.0+0.0im)),Qubit((0.0+0.0im,0.0+0.0im))])

6-element Array{Complex{Float64},1}:
 0.0+0.0im
 0.0+0.0im
 0.0+0.0im
 0.0+0.0im
 0.0+0.0im
 0.0+0.0im

In [7]:
H = BitwiseMatrixGate( (1/√2)*[1 1; 1 -1])
H | Qubit(0)
H | Qubit(1)

2-element Array{Complex{Float64},1}:
  0.707107+0.0im
 -0.707107+0.0im

In [4]:
X|b

LoadError: MethodError: no method matching |(::BitwiseMatrixGate, ::##1#2)
Closest candidates are:
  |(::Any, ::Any, ::Any, ::Any...) at operators.jl:138
  |(::BitwiseMatrixGate, ::Qureg) at In[3]:22
  |(::MatrixGate, ::Qubit) at In[3]:5
  ...

In [28]:
π*(3/8)^2 - 2*π*0.25^2 

0.04908738521234052